<?php

/** @var \AHT\ModuleHelloWorld\Block\Template $block */
?>

<div class="col-m-4">
    <fieldset class="fieldset admin__fieldset" id="theme">
        <div class="admin__field field" data-ui-id="theme-edit-tabstab-general-section-fieldset-element-form-field-theme-path">
            <label class="label admin__field-label"><span>Label</span></label>
            <div class="admin__field-control control">
                <div class="control-value">A value</div>
            </div>
        </div>

        <div class="admin__field field">
            <label for="test_input" class="label admin__field-label"><span>Test input</span></label>
            <div class="admin__field-control control">
                <input type="text" name="design[test_input]" id="test_input" title='Test input' class='input-text admin__control-text' />
            </div>
        </div>
    </fieldset>
</div>

<div class="col-m-4">
    <table class="admin__table-secondary">
        <tr>
            <th><?= __('First name') ?></th>
            <th>John</th>
        </tr>
        <tr>
            <th><?= __('Last name') ?></th>
            <th>Doe</th>
        </tr>
        <tr>
            <th><?= __("Email") ?></th>
            <th>john.doe@example.com</th>
        </tr>
        <tr>
            <th><?= __("Phone") ?></th>
            <th>000 000 000</th>
        </tr>
    </table>
</div>