<?php

/** @var \AHT\ModuleHelloWorld\Block\Template $block */
?>

<div class="page-actions">
    <div class="page-actions-inner">
        <div class="page-actions-buttons">
            <button class="action-primary" title="<?php __('Primary button') ?>">
                <?php echo __('Primary button') ?>
            </button>
            <button class="action-secondary" title="<?php echo __('Back') ?>">
                <?php echo __('Back') ?>
            </button>
        </div>
    </div>
</div>